apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetes-predictor
  template:
    metadata:
      labels:
        app: diabetes-predictor
    spec:
      containers:
        - name: diabetes-predictor
          image: fjukstad/diabetes-predictor
          ports:
            - containerPort: 8000
              name: plumber

---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-predictor
spec:
  ports:
    - port: 8000
  selector:
    app: diabetes-predictor
